matrix:
  - name: JSON
    aspell:
      lang: en
    dictionary:
      wordlists:
        - config/.skipwords.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - "**/*.json"
    default_encoding: utf-8
